### ISSUE TITLE
Additions to LMB Integration

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-lowermybills#10]
Please add the following fields to the integration. Please let me know if you would like this formatted another way and I'll be happy to do so. 

GrossMonthlyIncome --> monthly_salary
OccupationalStatus --> employment_status
EmployerName --> company.name
FirstMortgageBalance --> mortgage.first_mortgage_balance
FirstMortgageInterestRate --> mortgage.first_mortgage_rate
NeedPurchaseREAgent --> mortgage.application.is_working_with_realtor*

*This would be the only odd request to the integration as the following would apply:

If NeedPurchaseREAgent = yes, mortgage.application.is_working_with_realtor = no
If NeedPurchaseREAgent  = no, mortgage.application.is_working_with_realtor = yes

**Comment by zalary** [comment]
Do we have documentation on what field values will be passed for these?  Ideally all of these changes would be documented and reference-able in the available integrations docs.

**Comment by zalary** [comment]
we already support NeedPurchaseREAgent as described above.

**Comment by kcaponeAP** [comment]
Sure thing. Just discovered the correct docs.
https://drive.google.com/drive/#folders/0B36C7G4bQKsANVBIV0J3dVpHVWs

GrossMonthlyIncome - integer [10]

OccupationalStatus - string [75] 
Allowed values: Not Employed, Employed, Self-Employed, Retired

Employer - string [200]

FirstMortgageBalance - integer [12]

FirstMortgageInterestRate - deprecated 8/2013

NeedPurchaseREAgent - noted.  This contains a bug. Will open separate issue under velocity repo.

I've poured through the lead docs. They appear to be incomplete, with many updates, additions and deletions. If you need me to do more research, please let me know. Happy to go digging.

**Comment by zalary** [comment]
are we sure we need to capture and pass FirstMortgageInterestRate?  It's marked as deprecated as of 8/2013 and the docs we have do not indicate what, if anything, will be passed for this?

**Comment by kcaponeAP** [comment]
If it's deprecated, then please skip it.
