### ISSUE TITLE
PropertyFound Parameter

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-integration-lowermybills#13]
This integration needs to account for the PropertyFound parameter. It could be any of the following values: 

- Found Home, Signed Contract
- Found Home, No Contract
- PreQualification/PreApproval

We think it should map to mortgage.application.is_home_found, but open to suggestion here.

**Comment by alexkwolfe** [comment]
Yes. That is a fine idea. I wonder if another field (maybe called `is_contract_signed`) is in order. Then we could split this value into two fields. Not sure how that would play out when sending to Velocify or Mortech.

**Comment by cgrayson** [comment]
This seems related to https://github.com/activeprospect/leadconduit-integration-velocify/issues/21.

**Comment by ros3bud** [comment]
On hold for now as @kcaponeAP needs to research more.
