### ISSUE TITLE
Stop using deprectated fields

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-lowermybills#20]
I spotted a lead in production that had deprecated fields on it. We should replace these fields with the non-deprecated ones.

![image](https://cloud.githubusercontent.com/assets/569/7683313/e8776432-fd43-11e4-90e3-b9300ba0e3bb.png)

**Comment by alexkwolfe** [comment]
On second viewing it looks like the integration supports both. Can the deprecated ones be removed now? We'll need to check production flows where this integration is used to make sure those flows are no longer using the deprecated fields.

**Comment by kcaponeAP** [comment]
bump @alexj @alexkwolfe 

The lowermybills integration is still showing 3 deprecated fields:

http://docs.leadconduit.com/fields?q=lowermybills%20inbound

![screen shot 2015-08-03 at 5 49 31 pm](https://cloud.githubusercontent.com/assets/8238417/9049473/05a889c2-3a08-11e5-9953-7b219e7fd245.png)

**Comment by zalary** [comment]
resolved with Version 1.2.6
