### ISSUE TITLE
Stop populating deprecated fields

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-lowermybills#6]
The `mortgage.application.credit_rating` field is deprecated. There may be others as well.

**Comment by kcaponeAP** [comment]
Would you like these issues to be reported in the individual integrations? Seems best. I will be inspecting Credit Rating, Foreclosure and Bankruptcy for all integrations today.

**Comment by alexkwolfe** [comment]
Yes.

**Comment by kcaponeAP** [comment]
Damn waffle. i thought this was a note in all intergrations. i'll be bugging some massive stuff today. thanks in advance.
