### ISSUE TITLE
When downpayment is not included, result is NaN

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-lowermybills#7]
When downpayment is not populated, the result in Velocify is NaN

https://next.leadconduit.com/events/54d564806ed3d2d24c481ba6?event_id=54d564856ed3d2d24c481bad

(Client is B - message me for explanation in Slack if needed)

LMB: <DownPayment/>
Velocify: ...&down_payment_amount=NaN

**Comment by alexkwolfe** [comment]
This is a bug in the Velocify integration.

**Comment by kcaponeAP** [comment]
K. Closing.
